# Generated by Django 2.1.5 on 2019-01-25 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190125_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='images',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='product',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
